
//APP STATE ACTIONS
export const BEGIN_LOADING = 'BEGIN_LOADING';
export const END_LOADING = 'END_LOADING';

export const LOAD_IMAGE = 'LOAD_IMAGE';
export const UPDATE_LINE1_TEXT = 'UPDATE_LINE1_TEXT';
export const UPDATE_LINE1_ALIGNMENT = 'UPDATE_LINE1_ALIGNMENT';
export const UPDATE_LINE2_TEXT = 'UPDATE_LINE2_TEXT';
export const UPDATE_LINE2_ALIGNMENT = 'UPDATE_LINE2_ALIGNMENT';
export const UPDATE_LINE3_TEXT = 'UPDATE_LINE3_TEXT';
export const UPDATE_LINE3_ALIGNMENT = 'UPDATE_LINE3_ALIGNMENT';

//ALERT TEXT
export const SET_ALERT_TEXT = 'SET_ALERT_TEXT';
